# application.yaml

spring:
  profiles:
    active: dev
  application:
    name: blog_system
  datasource:
    url: jdbc:mysql://localhost:3306/account?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
      #validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
